### PR TITLE
Arush0311/mezz

### PR DESCRIPTION
**Pull request by arush0311**
This commit introduces mezzanine into the project and
creates rest endpoints for mezzanine blogs and categories

### CODE REVIEW

**Comment by arush0311** [comment]
we would want to merge it simultaneously with mozilla/science.mozilla.org#642

**Comment by arush0311** [comment]
Added management command for importing blogs derived from https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/blog/management/commands/import_wordpress.py.

Current To Do: 
1) Generate a plain text excerpt for each blog post
2) set is_staff status for each imported user
3) add users to blog_writers group

**Comment by arush0311** [comment]
we may want to do something like this https://blog.heroku.com/fork_your_data

**Comment by alanmoo** [comment]
Could we do something like that with #85 too, so that we can just clone the staging DB for the review deploy?

**Comment by arush0311** [comment]
Dont think so and heroku specifically warns against it. https://devcenter.heroku.com/articles/github-integration-review-apps#the-postdeploy-script

**Comment by arush0311** [comment]
We would want to have these env variables for s3 and github auth in both staging and production:
- USE_S3
- SOCIAL_AUTH_GITHUB_KEY
- SOCIAL_AUTH_GITHUB_SECRET
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_STORAGE_BUCKET_NAME
- AWS_S3_CUSTOM_DOMAIN
- AWS_LOCATION
- FILEBROWSER_DIRECTORY

**Comment by gideonthomas** [comment]
@arush0311, is this PR now not viable? Or does this still need review?

**Comment by arush0311** [comment]
Actually no. this will be broken down into several prs.

**Comment by arush0311** [comment]
End of gsoc marker :)

**Comment by gideonthomas** [comment]
ah I see, let me know if any of the smaller prs need review, I'm happy to help. Sorry for the delay on this one!

**Comment by alanmoo** [comment]
Sorry, Arush, this isn't getting in- as a Foundation we've shifted our focus to the main foundation.mozilla.org site and have abandoned Mezzanine.

**Pull request closed without merging**
